kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: lbischof/duplicacy-autobackup
    tags: armhf
    dockerfile: Dockerfile
    build_args:
      - platform=arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
