
name: Build Docker image

on:
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: duplicacy-autobackup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        severity: 'CRITICAL,HIGH'
        format: 'table'
